name: Generate and deploy
on: [push]

jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Generating static pages
        run: hugo

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Moving static pages to web server
        run: ls
